### ISSUE TITLE
Add question id, make choice window bigger, put options in right order

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/survey_admin#14] opened 2017-10-27 21:29 UTC
![survey admin issues](https://user-images.githubusercontent.com/29083044/32125966-1e6210d4-bb0a-11e7-8675-58d64a390565.PNG)

**Comment by carlosparadis** [comment] 2017-10-27 21:35
@eileenpeppard I am passing the ball to this to @jygh98 since he was the one that looks at Allie's code before getting started in scrape-utils and @ryantanaka is already assigned to the design of survey_display.

**Comment by carlosparadis** [comment] 2017-10-27 21:39
@jygh98 Before you start working on this, make sure you:

1. Fork the most current version of this repo (there is a fork button in the top right). 
1. Git clone **your fork** into your computer.
1. Access the folder you just git clone in your computer with `Git Bash`, then type `git branch -b 14-response-order-position-display`. 

This will separate any changes you do in the folder to this branch. You know the drill on the commits and @ryantanaka can help you on this or me. I would recommend one commit for each of the features requested by Eileen here:

* Add question id
* make choice window bigger
* put options in right order

So solve one problem at a time and commit :)

**Again please use `git status` to avoid sending hundreds of files to Git**. Also, needless to stay: Do **not** edit anything directly in the server, as we will be unable to keep track of the changes.

On the meantime, I need to clean the server side to make sure this runs fine.

**Comment by carlosparadis** [comment] 2017-11-16 10:02
@eileenpeppard Spoke with Jason today (over phone) about this while he was at the office. Things moved a bit forward on where the problem lies, but nothing concrete yet. So the rest of this comment will just look like gibberish to you so ignore :-) 

 @jygh98 Summarizing what we discussed today:

- The box @eileenpeppard wants bigger is the one loaded in https://github.com/erdl/survey_admin/blob/7f66d44887a41802f515581db65c536a067b9327/ubuntuStation/templates/survey_form.html#L18-L20 which is under div-class as we can see in the code box above. 

The problem starts here. We don't know exactly what has control over the box. The current contestants are:

## The .css file 

If we believe the box size is responsibility of the .css then the follow-up is 

https://github.com/erdl/survey_admin/blob/7f66d44887a41802f515581db65c536a067b9327/ubuntuStation/templates/survey_form.html#L18
The div-class. 

But because life isn't miserable enough 🌧 there are not 1, nor 2 but THREE .css files with the same name all containing the same div:

https://github.com/erdl/survey_admin/search?utf8=%E2%9C%93&q=form-group&type= 😞 . 

You know, after today I am institutionalizing the `wtf?` tag. 

Well, best of luck :P 

## The forms_wtf library

If instead, we believe the box size is the responsibility of the form library being used then the follow-up is: 

https://github.com/erdl/survey_admin/blob/7f66d44887a41802f515581db65c536a067b9327/ubuntuStation/views.py#L118-L145

which in turns begs the definition of the class which is in:

https://github.com/erdl/survey_admin/blob/7f66d44887a41802f515581db65c536a067b9327/ubuntuStation/forms.py#L32-L42

Which in turns imports from `FlaskForm`, which is from `flask_wtf`:

https://github.com/erdl/survey_admin/blob/7f66d44887a41802f515581db65c536a067b9327/ubuntuStation/forms.py#L1

Documentation for the class is [here](https://flask-wtf.readthedocs.io/en/stable/api.html#module-flask_wtf).

@ryantanaka may want to help us with this if you used this stuff before. Just seeing this chain of dependencies makes me feel dizzy 💫 

# p.s.: 
Also for future reference, use permalinks from the repo itself in case you have to delete the fork, it won't break the links on the issues.

**Comment by jygh98** [comment] 2017-11-18 01:18
# Adjusting choice screen to be bigger
So for making the choice box bigger, instead of trying to dig through the various css files and libraries i decided to view the page elements directly by right clicking the page and clicking view source.  The html debugger will open up like so

![image](https://user-images.githubusercontent.com/25787662/32975142-6d50bd36-cba8-11e7-938d-33cce59ce748.png)

If you see on the left, the height is currently set to auto and it even tells you which line of the css file it is looking for! Also i am able to directly mess with the code in the debugger and be able to instantly see what it changes which is so much better than playing around in the css file and having to restart the client every time i want to make a change.  So i changed the height to 450px and also adjusted the width to 300px as the box in general seemed a bit small.  

Unfortunately these changes are static so as we add more questions we would have to manually adjust the height/width every time.  

Also a quick note for documentation purposes, to run the admin dashboard run locally you would need to change [run.py](https://github.com/erdl/survey_admin/blob/master/run.py#L5) from

>`app.run(debug=True, host='0.0.0.0', port=8080)`
to
>`app.run(debug=True, host='localhost', port=8080)`

I swear we documented this somewhere but i couldn't find it when i was trying to deploy the dashboard locally.

**Comment by carlosparadis** [comment] 2017-11-28 20:42
https://github.com/erdl/survey_display/issues/30

is a duplicate of ` put options in right order` portion of this issue title. Currently, the existing ordering is done alphabetically in `survey_display`, however, this can be modified to use the column where we specify the order of the questions in the database in `survey_display` as it was done with this commit for survey_display:

https://github.com/erdl/survey_display/commit/33f9bdf24bf21147446f6ed1ff709e976e9a703b

**Comment by carlosparadis** [comment] 2017-12-28 06:10
@jygh98 confirmed all the requested changes were applied. Closing issue.

**Closed as completed by carlosparadis** 2017-12-28 06:10 UTC
Labels: enhancement, wtf?, stat:in progress, prio:high
