### ISSUE TITLE
I need to edit question text - how do I refresh the question on the kiosk/admin?

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/survey_admin#15] opened 2017-11-15 02:46 UTC
Hi, Guys.

Jim wanted an edit on a question and I changed it in the database but don't see a change on the kiosk.  I changed "How acceptable is the temperature" to "How acceptable is the room temperature"

Not sure what the process is to see the change.

Thanks!

**Comment by carlosparadis** [comment] 2017-11-15 03:55
The problem is that your sequence of steps is incomplete: You added a question, but forgot to replace in the desired survey one question for the other. I already fixed, and should be displaying correctly now on `test1kiosk`. Please see the sequence of steps below and **let me know if it makes sense so I can close the issue**. 

---------------------

> and I changed it in the database 

I am `guessing` these are the 2 pages you hoped to see a change:

- [survey_admin](http://csbcd01.soest.hawaii.edu/survey/70) does not display the new question text.
- [survey_display](http://csbcd01.soest.hawaii.edu/surveys/test1kiosk) does not display the new question text. 

However, I don't see within `survey_admin` any means to edit a survey by removing questions and adding questions. If you are trying to do this in the database, from the link above for Survey_Admin in the top it says the survey name is:

`AccTemp-Kiosk`

Then, going over the `survey_info` table:

`select * from survey_info;`

, I can see that survey has `survey_info_id_70`. 

Then seeing what questions are available for this survey:

`kiosk=> select * from survey_question where survey_info_id = 70;`

The only id mapped to it was `question_id 8` (now it is 1 because I edited it). 

You can then check the list of questions

`select * from question;`

And you will see this is the question before you edited. 

What I did was then change the `8` to `1` like so: 

`UPDATE survey_question SET question_id = 1 WHERE survey_info_id = 70`  

See [Update Manual](https://www.postgresql.org/docs/8.2/static/sql-update.html) for more details, but it is just the SQL command to a normal edit in NavCat.

-------

In the future, if the idea is to really edit an old question, then go to the `question` table in the kiosk database and edit it instead of adding a new question. 

Before we deploy this, we should really clean up all these chopped off questions before we are too confused on what uses what or what they are about.

**Comment by eileenpeppard** [comment] 2017-11-15 20:45
Oh, my God, I am too tired to read this! i wanted to edit the existing question, not add a question. I did it directly in the database but did not see it get updated on the kiosk display.

**Comment by carlosparadis** [comment] 2017-11-15 22:39
@eileenpeppard I am trying to teach you how to diagnose the problem and solve it so you don't need to rely on me for a task that will likely be recurrent, as Jim will be asking you to do this when the time comes. If I didn't think it was recurrent, I wouldn't try to explain.

Since I already solved the problem, just try to go back to this issue when you have it again. I will explain to you when I am in the office, but I think it is best it is written since you (and I) will forget the details on the long-run.

**Comment by eileenpeppard** [comment] 2017-11-15 23:00
Okay, let's talk when you are in the office. When i get time I'll look at this again.

**Comment by carlosparadis** [comment] 2017-11-16 00:23
For the record, we discussed in the office about this issue. The summary is as follows:

## Important Protocol to follow when modifying questions 

- We agreed that if **during deployment** a new question needs to be changed, it **should NOT** be modified directly. Instead, a new question should be added, and the **survey** should now point to the new question instead. This is necessary so we have the log of the question the old participants were responding to. If we edit the original question, it will be **lost**. 

- We agreed that **when NOT in deployment** (i.e. it's not actively being used in an experiment), we can and should fix the questions as to avoid changing them later. 

## Current state 

Because it is not in deployment, we reverted the current question to as it was and edited the question itself. 

When doing so, we realized that the [screen from the tablet did not update](https://github.com/erdl/survey_display/issues/19). While conceptually this makes sense, as the HTML page being displayed was downloaded before, @eileenpeppard believes that answering a new response does **NOT** update to the new question. Pressing the home button refreshes it, but adds a necessary manual step for someone to come in. This is very undesirable. @ryantanaka this should be tested and followed up in the linked issue. 

## This issue does not relate directly to survey_admin CODE

At the end of the day, we did not modify anything at `survey_admin`. This issue is actually related to the database of `kiosk` itself and how both web applications reason the data model. A question was modified in the database, but it was not the one both web applications were referring to, hence the mismatch in expectations for it to update (plus the issue of refresh in the kiosk).

**Closed as completed** 2017-11-16 00:23 UTC
Labels: documentation
